### ISSUE TITLE
Fancy editor suggestions is not showing "pokémon" when it should

### ISSUE THREAD

**Issue by HushedFox** [furbooru/philomena#18]
Even though "`pokemon`" is aliased to "`pokémon`":
![image](https://user-images.githubusercontent.com/17304608/88230973-a6cd5000-cc73-11ea-86c9-ee3e34aea4e7.png)
fancy tag editor suggestions is not showing the aliased `pokémon` when typing in `pokemon`:
![image](https://user-images.githubusercontent.com/17304608/88230942-987f3400-cc73-11ea-8d91-90dcf750db21.png)
but it works as intended with aliases of other tags:
![image](https://user-images.githubusercontent.com/17304608/88231253-2f4bf080-cc74-11ea-8ff1-839555b5cc2e.png)

Today I even noticed that the `pokémon` tag is not showing up when typing in just `pok`:
![image](https://user-images.githubusercontent.com/17304608/88231082-e005c000-cc73-11ea-8561-4faa29dbbcbc.png)

But after some time it did:
![image](https://user-images.githubusercontent.com/17304608/88231119-ed22af00-cc73-11ea-9363-85cae4f7600d.png)

**Comment by liamwhite** [comment]
Working for me
