### ISSUE TITLE
New tag category for body forms.

### ISSUE THREAD

**Issue by Fleetfoot** [furbooru/philomena#35]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem but given the wider reach of the furry fandom in comparison to MLP alone it feels appropriate to add a new tag category for body forms as it is an important heavily used tag on search, filtering and watch and hence added visibility is welcome.

**Describe the solution you'd like**
It was considered creating a new tag category "Body Form" that should come right after "Species" in the category hierarchy, tag colour could be grey as it is distinctive enough from present category colours. It'd englobe all applicable body form tags such as anthro, semi-anthro, feral, lifelike feral, taur, humanoid etc. 

**Describe alternatives you've considered**
There's no alternative other than leaving them as green uncategorised tags which is not ideal, sometimes the lesser used Body Form tags are missed such as semi-anthro and taur since they are undistinguishable among the other green ones causing inconvenience and doubt.

**Comment by Meow** [comment]
Closed via #5c87f2b
