### ISSUE TITLE
Inserting a blockquote on a text that ends with a link breaks the quote and the link

### ISSUE THREAD

**Issue by HushedFox** [furbooru/philomena#36]
**Describe the bug**
When the text that should go into a quote ends with a link and a quote is inserted the quote doesn't work unless a space is manually added between the link and the `[/bq]` or that part is moved to a new line.

**To Reproduce**
1. Go to any page that let's you edit and preview text, for example https://furbooru.org/images/new
2. Write a text with a link in it, for example this:
`"This is a link to Site Rules":https://furbooru.org/pages/rules`
![image](https://user-images.githubusercontent.com/17304608/93001518-d724c280-f52f-11ea-917f-96c9976407be.png)
3. Select all and click on "insert blockquote":
![image](https://user-images.githubusercontent.com/17304608/93001603-65994400-f530-11ea-9066-532197362a03.png)
the end result is:
![image](https://user-images.githubusercontent.com/17304608/93001528-ee63b000-f52f-11ea-90da-725055efbf39.png)
4. Preview the description/comment/forum post and see that the qoute is broken and the link is wrong (because the link now leads to an url that has `[/bq]` added at the end):
![image](https://user-images.githubusercontent.com/17304608/93001546-0b987e80-f530-11ea-974c-09558bbe7cc0.png)

**Expected behavior**
The quote and the link should work. A solution would be adding a space:
![image](https://user-images.githubusercontent.com/17304608/93001557-19e69a80-f530-11ea-81bc-4af15c9dbcf6.png)

or moving `[/bq]` to a new line:
![image](https://user-images.githubusercontent.com/17304608/93001564-223ed580-f530-11ea-97b4-b6c2ebc78ab0.png)

It should be done automatically when clicking on "insert blockquote".

**Comment by SeinopSys** [comment]
I believe this is a known issue, the usual workaround I've used is to wrap the link in `[]`:

```
[bq]["This is a link to Site Rules":https://furbooru.org/pages/rules][/bq]
```

Hopefully this will be resolved by the eventual move to markdown

**Comment by HushedFox** [comment]
It's easier to just add one space or move `[/bq]` to a new line by hiting enter once than to add two different symbols in tow different parts of the link (`[` and `]`) :P

**Comment by SomewhatDamaged** [comment]
> I believe this is a known issue, the usual workaround I've used is to wrap the link in `[]`:
> 
> ```
> [bq]["This is a link to Site Rules":https://furbooru.org/pages/rules][/bq]
> ```
> 
> Hopefully this will be resolved by the eventual move to markdown

Perhaps it would be better to make the `Link` button automatically wrap URLs in `[` `]`?
