### ISSUE TITLE
Improve user understanding of merge/update report functonality.

### ISSUE THREAD

**Issue by Fleetfoot** [furbooru/philomena#37]
**Is your feature request related to a problem? Please describe.**
On Furbooru we have newer users who have never used Derpibooru hence they are unaware of how reporting duplicates works, there's been a great influx on the standard report queue for duplications instead of the right route.

**Describe the solution you'd like**
There should be made clearer to users, options considered are rewrite the button text to Update/Merge of Duplications in addition to add a text in front of it explaining for example: _**Is this image already on the site ? Did you upload an updated version? Report image duplications here!**_   

**Describe alternatives you've considered**
While it's doable it is not ideal to handle these images through the conventional report queue, we lack ways to properly teach people of the difference between the two types of report outside individually DM'ing them.

**Comment by Meow** [comment]
Added via 2ff4939e8d5809d99540d59abe9c83fa3c30c6c2
