### ISSUE TITLE
"Fetch" button on upload page is labeled "undefined"

### ISSUE THREAD

**Issue by TheSmilingPony** [furbooru/philomena#38]
**Describe the bug**
The "Fetch" button in the URL image field on the upload/new page is labeled "undefined" when the page first loads; it switches to "Fetch" after use.

**To Reproduce**
1. Go to /new
2. Observe "Fetch" button is labeled "undefined"

**Expected behavior**
Button is labeled "Fetch"

**Screenshots**
![image](https://user-images.githubusercontent.com/2158409/94365021-df533500-00cd-11eb-945c-fcfc59aec298.png)

**Comment by liamwhite** [comment]
This has long since been fixed, Furbooru hasn't merged upstream in a while though
