### ISSUE TITLE
UX: Alignment issue

### ISSUE THREAD

**Issue by wolfhowlmedia** [furbooru/philomena#6]
Description:
It's an alignment issue in one of the navigation panels, namely the one that pertain the image layout itself.
Example here: https://furbooru.org/images/7398 (I pick the best images, I know)

The offending panel is this:
![image](https://user-images.githubusercontent.com/56067495/87228727-5caabb80-c3a3-11ea-8704-bc6a64b142c3.png)

as its form doesn't any function.

The rest of the page text happily follows left- or right-alignment, as pictured here:
![image](https://user-images.githubusercontent.com/56067495/87228947-c8415880-c3a4-11ea-9133-d8495086a2b5.png)
and
![image](https://user-images.githubusercontent.com/56067495/87229169-3a666d00-c3a6-11ea-955c-0d9a9afd992c.png)

How should it look like?
![image](https://user-images.githubusercontent.com/56067495/87229190-7dc0db80-c3a6-11ea-99a4-6b109664cb3a.png)
(basically just "left aligned")

**Comment by Meow** [comment]
I believe this is intentional. The entire UI/UX is slated to be re-done in the future anyway, but for now I would leave it as it is.
